# private/work ssh hosts.
# applied to ~/.ssh/config.d/target.conf by the work profile and included first
# by the base ~/.ssh/config, so hosts defined here take precedence.

Host github-ghec
  HostName github.com
  IdentityFile ~/.ssh/id_ed25519_ghec

Host git.target.com
  HostName git.target.com
  User DavidVader
  AddKeysToAgent yes
  IdentityFile ~/.ssh/id_ed25519_tgt
  IdentitiesOnly yes
